import type { Metadata } from 'next';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { Inter } from 'next/font/google';
import { AuthProvider } from '@/components/auth';
import { StyledEngineProvider } from '@mui/material';
import CssBaseline from '@mui/material/CssBaseline';

import './globals.css';
import SidebarLayout from '@/components/sidebar-layout';
import { scanInstalledModules } from '../lib/installed-modules';
import { getSidebarJson } from '../lib/sidebar-structure';
import React, { ReactNode } from 'react';
import { getAuthProviderId } from '@/auth';
import { ToastContextProvider } from '@/components/toast-provider';
import UserSettingsProvider from '@/components/user-settings-context';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Timesense Platform',
    description: 'Generated by create next app',
};

const sidebarData = getSidebarJson(scanInstalledModules().modules);

export default async function RootLayout({
    children,
}: Readonly<{ children: ReactNode }>) {
    return (
        <html>
            <body className={inter.className} style={{ margin: '0px' }}>
                <AppRouterCacheProvider options={{ key: 'css' }}>
                    <AuthProvider>
                        {/* CssBaseline kickstart an elegant, consistent, and simple baseline to build upon. */}
                        <CssBaseline />
                        <StyledEngineProvider injectFirst>
                            <ToastContextProvider>
                                <UserSettingsProvider>
                                    <SidebarLayout
                                        sidebar={sidebarData}
                                        provider={getAuthProviderId()}>
                                        {children}
                                    </SidebarLayout>
                                </UserSettingsProvider>
                            </ToastContextProvider>
                        </StyledEngineProvider>
                    </AuthProvider>
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
